### ISSUE TITLE
Supprimer les elements selectionné

### ISSUE THREAD

**Issue by math-pixel** [IlanOu/portfolio-json-generator#1]
- Pouvoir supprimer une photo qui a été ajouter
- Pouvoir supprimer une vidéo qui a été ajouter

Sans re commencer tout le json en cour

**Comment by IlanOu** [comment]
C'est fait, pour la photo, il faut cliquer sur l'image (oui c'est pas forcément clair)
Pour la vidéo, tu cliques sur l'image vidéo.
